[MKC-1311] [MKC-1312] Add compatible hardware to Mouse & Keyboard
arduino/reference-en pull request #935
Opened 2023-11-20 09:29 UTC by Hannes7eicher

This PR adds a table of compatible hardware for the keyboard and mouse language reference.

2023-11-20 09:51 UTC, karlsoderby commented on Language/Functions/USB/Keyboard.adoc
> +| Board                | Pins
Looks good. I think, let's not link all MKR boards, but instead link to the family, like this: `https://docs.arduino.cc/#mkr-family`.

2023-11-20 09:53 UTC, karlsoderby commented on Language/Functions/USB/Keyboard.adoc
> +| Board                | Pins
```suggestion
| Board                | Supported Pins                     
```

2023-11-20 09:54 UTC, karlsoderby commented on Language/Functions/USB/Keyboard.adoc
> +| link:https://docs.arduino.cc/hardware/micro[Micro]                   | Digital / Analog Pins
Let's change `Digital / Analog Pins` to `All digital & analog pins

2023-11-20 09:54 UTC, karlsoderby requested changes
Looks good! Couple of suggestions before we can merge!

2023-11-20 11:20 UTC, karlsoderby approved these changes

2023-11-20 11:20 UTC, merged

2024-04-28 20:12 UTC, per1234 commented
@Hannes7eicher @karlsoderby really??????

What makes you think pins are relevant to the subject of HID?

What sort of verification did you do for the list of boards? These libraries do not support the Nano ESP32 and GIGA R1 WiFi, which you would have learned by simply attempting to compile any sketch that uses either library for these boards.